### ISSUE TITLE
Fense class not found.

### ISSUE THREAD

**Issue by komatta-san** [wsntxxn/AudioCaption#5]
Thank you for sharing your code. I was trying to reproduce your results. I managed to train the model but I had some problems with the evaluation.

When running,
```
python captioning/pytorch_runners/run.py evaluate $EXP_PATH configs/clotho_v2/waveform/test.yaml
```
the `Fense` class is not found.

```
Traceback (most recent call last):                                                                  nv_block6.bn2.num_batches_tracked'])
  File "captioning/pytorch_runners/run.py", line 381, in <module>
    fire.Fire(Runner)
  File "/home/koma/mambaforge/envs/caps/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/koma/mambaforge/envs/caps/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/koma/mambaforge/envs/caps/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/koma/work/captioning/AudioCaption/captioning/pytorch_runners/base.py", line 324, in evaluate
    from fense.fense import Fense
ModuleNotFoundError: No module named 'fense.fense'

```

I checked the `Fense` class is not defined in your code nor the original fense repo. https://github.com/blmoistawinde/fense

**Comment by wsntxxn** [comment]
Hi, I have just uploaded the script to the original repo: https://github.com/blmoistawinde/fense/blob/main/fense/fense.py. If you have any further questions, please be free to connect with me.
